include ../Makefile.tests_common
USEMODULE += io1_xplained
USEMODULE += xtimer
USEMODULE += sdcard_spi
USEMODULE += fmt
USEMODULE += shell
FEATURES_BLACKLIST += arch_msp430

include $(RIOTBASE)/Makefile.include
